- name: Deploy to Touge Server via SSH
  run: |
    mkdir -p ~/.ssh && chmod 700 ~/.ssh
    echo "${{ secrets.TOUGE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    
    # 1. 扫描主机密钥：用TOUGE_SSH_PORT变量
    ssh-keyscan -p ${{ secrets.TOUGE_SSH_PORT }} -H ${{ secrets.TOUGE_SERVER_IP }} >> ~/.ssh/known_hosts
    echo "SSH环境配置完成"
    
    # 2. SSH连接：用TOUGE_SSH_PORT变量
    ssh -v -p ${{ secrets.TOUGE_SSH_PORT }} -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa root@${{ secrets.TOUGE_SERVER_IP }} << 'EOF'
      set -e
      cd /root/flask-web-app || { echo "项目目录不存在"; exit 1; }
      git pull origin main || { echo "Git拉取失败"; exit 1; }
      pip3 install -r requirements.txt || { echo "依赖安装失败"; exit 1; }
      supervisorctl restart flask-web-app || { echo "应用重启失败"; exit 1; }
      supervisorctl status flask-web-app
      echo "部署完成"
    EOF
  env:
    TOUGE_SSH_PRIVATE_KEY: ${{ secrets.TOUGE_SSH_PRIVATE_KEY }}
    TOUGE_SERVER_IP: ${{ secrets.TOUGE_SERVER_IP }}
